#!/bin/bash

set -e; set -o pipefail

function format(){
 toFormat=$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ ".go" {print $2}' )
 echo "files to format: $toFormat"

 for f in $toFormat; do
   (go fmt "$f"; git add "$f") &
 done

 wait
}

function tidy(){
  go mod tidy
  git add go.mod
  git add go.sum
}

tidy
format
