version: "3.3"
services:
  app:
    build:
      context: .
    ports:
      - "7080:7080"
    environment:
      - "LOGIC_PORT=7080"
      - "TRACE_GRPC_URL=tempo:4317"
  grafana:
    image: grafana/grafana:9.2.4
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
      - ./docker/grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
  loki:
    image: grafana/loki:2.7.0
    command: "-config.file=/etc/loki/local-config.yaml"
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.7.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./docker/promtail/docker-config.yaml:/etc/promtail/docker-config.yml
    command: "-config.file=/etc/promtail/docker-config.yml"
  prometheus:
    image: prom/prometheus-linux-amd64:v2.40.2
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
  tempo:
    image: grafana/tempo:1.5.0-amd64
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - "./docker/tempo/tempo.yml:/etc/tempo.yml"
    ports:
      - "4317:4317"  # otlp grpc