version: "3.3"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
  grafana:
    image: grafana/grafana:9.2.4
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
      - ./docker/grafana/dashboards/:/var/lib/grafana/dashboards/
  loki:
    image: grafana/loki:2.7.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.7.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./docker/promtail/docker-config.yaml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
  prometheus:
    image: prom/prometheus-linux-amd64:v2.40.2
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/:/etc/prometheus/