global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ] # monitor itself
  - job_name: "static"
    static_configs:
      - targets:
          - "app:9090"
          - "loki:3100"