apiVersion: 1

deleteDatasources:
  - name: Loki
  - name: Tempo
  - name: Prometheus

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    uid: loki
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: "tempo"
          matcherRegex: 'TraceID\"\:\"(\w+)\"'
          name: TraceID
          url: '$${__value.raw}' #will be interpreted as tempo query
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    uid: "tempo"
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        tags: [ 'job', 'container']
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [ { key: 'service.name', value: 'service' }, { key: 'job' } ]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(tempo_spanmetrics_latency_bucket{$__tags}[5m]))'
        serviceMap:
          datasourceUid: 'prometheus'
      search:
        hide: false
      lokiSearch:
        datasourceUid: 'loki'
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    uid: 'prometheus'
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceId