apiVersion: 1

deleteDatasources:
  - name: Loki
  - name: Tempo

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    uid: loki
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: "tempo"
          # TODO link from Loki to Tempo does not work
          # potential reasons - tempo.tracesToLogs.tags, tags mapping?
          matcherRegex: 'TraceID\\"\\:\\"(\\w+)\"'
          name: TraceID
          url: '$${__value.raw}' #will be interpreted as tempo query
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    uid: "tempo"
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        tags: [ 'job', 'instance' ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      #      tracesToMetrics:
      #        datasourceUid: 'prometheus'
      #        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
      #        queries:
      #          - name: 'Sample query'
      #            query: 'sum(rate(tempo_spanmetrics_latency_bucket{$__tags}[5m]))'
      #      serviceMap:
      #        datasourceUid: 'prometheus'
      search:
        hide: false
      #      nodeGraph:
      #        enabled: true
      lokiSearch:
        datasourceUid: 'loki'