apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceId
